[alias]
build-x86-none = "build --target targets/x86_64-yarm-none.json"
check-x86-none = "check --target targets/x86_64-yarm-none.json"

[env]
YARM_X86_64_NONE_TARGET = "targets/x86_64-yarm-none.json"
